# if you do not use Apollo, ignore the follow config
######################### Apollo config start #####################################
apollo:
  # if use Apollo set this flag to true
  enabled: false
  bootstrap:
    # if use Apollo set this flag to true
    enabled: false
    namespaces: application
    eagerLoad:
      # if use Apollo set this flag to true
      enabled: false
######################### Apollo config end #######################################

# if you do not use Nacos, ignore the follow config
######################### Nacos config start ######################################
nacos:
  config:
    # if use Nacos config set this flag to true
    enabled: false
    # need replace
    server-addr: localhost:8848
    auto-refresh: true
    group: fizz-gateway
    data-id: application
    type: PROPERTIES
    # need replace
    namespace: c37ecd3b-e8b3-42cc-ba94-98e931e33683
  discovery:
    # if use Nacos discovery set this flag to true
    enabled: false
    # need replace
    server-addr: localhost:8848
    auto-register: true
    register:
      group-name: fizz-gateway
######################### Nacos config end #######################################

# if you do not use Eureka, ignore the follow config
######################### Eureka config start ####################################
eureka:
  client:
    # if use Eureka set this flag to true
    enabled: false
    serviceUrl:
      # need replace
      defaultZone: http://localhost:6600/eureka/
  instance:
    prefer-ip-address: true
######################### Eureka config end ######################################

server:
  port: 8600
spring:
  profiles:
    active: dev
  application:
    name: fizz-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

aggregate:
  redis:
    # need replace
    host: localhost
    # need replace
    port: 6379
    # need replace
    password: 123456
    # need replace
    database: 9
proxy-webclient:
  name: proxy
aggr-webclient:
  name: aggr
fizz-web-client:
  timeout: 20000
log:
  headers: COOKIE,FIZZ-APPID,FIZZ-SECRETKEY,FIZZ-SIGN,FIZZ-TS,FIZZ-RSV

